# Translations template for vigilo-vigiconf.
# Copyright (C) 2011 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2011-01-06 14:50+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/vigiconf/commandline.py:74
#, python-format
msgid "ERROR: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:77
msgid "No server to manage."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:139
msgid ""
"Vigilo server management is only available in the Enterprise edition. "
"Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:159
msgid "usage: "
msgstr ""

#: src/vigilo/vigiconf/commandline.py:160
#, python-format
msgid "conflicting option string(s): %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:161
msgid "subcommands"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:162
#, python-format
msgid "unrecognized arguments: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:163
msgid "expected one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:164
msgid "expected at most one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:165
msgid "expected at least one argument"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:166
#, python-format
msgid "expected %s argument(s)"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:167
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:168
msgid "positional arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:169
msgid "optional arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:170
msgid "too few arguments"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:171
#, python-format
msgid "argument %s is required"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:172
#, python-format
msgid "one of the arguments %s is required"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:173
#, python-format
msgid "%s: error: %s\n"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:174
msgid "show this help message and exit"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:175
msgid "show program's version number and exit"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:179
msgid "Debug mode."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:181
msgid "Don't try to switch to the correct user."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:186
msgid "Vigilo configuration manager"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:187
msgid "Subcommands"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:193
msgid "Prints a summary of the current configuration."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:196
msgid "Supervision servers to query, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:203
msgid "Application status management."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:207
msgid "Stop the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:209
msgid "Start the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:211
msgid "Restart the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:213
msgid "Applications to manage, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:235
msgid "Deploys the configuration on each server if the configuration has changed."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:239
msgid "Stop the process after the file generation, before pushing the files."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:242
msgid ""
"Stop after pushing the files to the remote servers, and before restarting the"
" services."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:245
msgid "Deploy the given revision"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:247
msgid "Force the immediate execution of the command. Do not wait. Bypass all checks."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:250
msgid "Simulate only, no copy will actually be made, no commit in the database."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:253
msgid "Supervision servers to deploy to, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:260
msgid "Discover the services available on a remote server."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:265
msgid "Output file. Default: standard output."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:267
#, python-format
msgid "SNMP community. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:269
#, python-format
msgid "SNMP version. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:271
#, python-format
msgid "Main group. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:273
msgid ""
"Hosts or files to scan. The files must be the result of an snmpwalk command "
"on the '.1' OID with the '-OnQe' options."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:281
msgid "Enables or disables a Vigilo server"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:284
msgid "Don't re-deploy the configuration, only set the status."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:287
msgid "New status"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:289
msgid "Server name(s) to enable/disable"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:300
msgid "VigiConf was launched as user 'root'. Switching to user 'vigiconf' instead."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:305
msgid "Unable to switch to user 'vigiconf'. Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:329
msgid "VigiConf was not launched as user 'vigiconf'. Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:362
#, python-format
msgid ""
"Can't obtain lock on lockfile (%(lockfile)s). VigiConf already running ? "
"REASON : %(error)s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:375 src/vigilo/vigiconf/commandline.py:377
#, python-format
msgid "VigiConf error: %s"
msgstr ""

#: src/vigilo/vigiconf/conf.py:299
msgid "Error loading configuration"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:78
#, python-format
msgid "%s: No such file"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:123
msgid "The \"snmpwalk\" command is not installed."
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:126
#, python-format
msgid ""
"SNMP walk command failed with error status %(status)s and message:\n"
"%(msg)s\n"
"The command was: %(cmd)s"
msgstr ""

#: src/vigilo/vigiconf/applications/nagios_hls/generator.py:71
msgid "No server has been configured to host High-Level Services"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:223
#, python-format
msgid "Can't find the validation script for app %(app)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:261
#, python-format
msgid "%(app)s: validation failed for server '%(server)s': %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:268
#, python-format
msgid "%(app)s : Validation successful for server: %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:312
#, python-format
msgid "%(app)s : Qualification failed on '%(server)s' - REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:320
#, python-format
msgid "%(app)s : Qualification successful on server : %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:363
#: src/vigilo/vigiconf/lib/application.py:387
#, python-format
msgid "%s : Start process failed."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:399
#, python-format
msgid "Starting %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:408
#, python-format
msgid "Can't Start %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:416
#, python-format
msgid "%(app)s started on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:456
#: src/vigilo/vigiconf/lib/application.py:480
#, python-format
msgid "%s : Stop process failed."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:492
#, python-format
msgid "Stopping %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:501
#, python-format
msgid "Can't Stop %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:509
#, python-format
msgid "%(app)s stopped on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:173
#, python-format
msgid ""
"Incoherent configuration: application %(app)s has an entry point named "
"%(epname)s in package %(eppkg)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:178
#, python-format
msgid "Application %s is installed but disabled (see conf.d/general/apps.py)"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:182
#, python-format
msgid "Application %s is not unique."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:183
#, python-format
msgid " Providing modules: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:192
#, python-format
msgid "Application %s has been added to conf.d/general/apps.py, but is not installed"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:236
msgid "Generation failed!"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:239
msgid "Generation successful"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:244
msgid "Validation Successful"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:249
msgid "Commit Successful"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:258
msgid ""
"You can't go back to a former revision if you have modified your "
"configuration. Use 'svn revert' to cancel your modifications"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:272
#, python-format
msgid "Can't get the SVN status for the configuration dir: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:290
msgid "Not updating because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:311
#, python-format
msgid "Can't add %(path)s in repository: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:327
#, python-format
msgid "Can't remove %(path)s from repository: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:335
msgid "Not committing because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:347
#, python-format
msgid "Can't commit the configuration dir in SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:362
#, python-format
msgid ""
"Can't execute the request to update the local copy. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:404
#, python-format
msgid "Can't execute the request to get the current revision: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:476
msgid ""
"The configurations files have not been transfered on every server. See above "
"for more information."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:528
msgid "All servers are up-to-date, no deployment needed."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:640
msgid "Switch directories was not successful on each server."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:667
msgid "All servers are up-to-date. No restart needed."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:687
msgid "Stop applications failed"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:704
msgid "Start applications failed"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:709
#, python-format
msgid "Current revision in the repository : %d"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:717
msgid "(should be deployed)"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:719
msgid "(should restart)"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:720
#, python-format
msgid "Revisions for server %(server)s : %(rev)s%(dep)s%(restart)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator.py:726
#, python-format
msgid "Cannot get revision for server: %(server)s. REASON : %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:117
msgid "Server name set to None."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:119
msgid "Server name incorrect (length = 0)."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:179
msgid "Unknown command type."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:196
#, python-format
msgid "The source file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:213
#: src/vigilo/vigiconf/lib/remotecommand.py:246
msgid "Cannot reach server."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:216
#: src/vigilo/vigiconf/lib/remotecommand.py:248
msgid "Cannot find file."
msgstr ""

#: src/vigilo/vigiconf/lib/revisionmanager.py:169
#, python-format
msgid "Cannot write the revision file: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:83
msgid "On the Community Edition, you can only use localhost"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:178
#, python-format
msgid ""
"Can't activate the configuration on %(server)s. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:204
#, python-format
msgid "Can't tar config for server %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:222
#, python-format
msgid "%s : deployement successful."
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:236
#, python-format
msgid "Cannot copy files (%(from)s to %(to)s): %(error)s."
msgstr ""

#: src/vigilo/vigiconf/lib/systemcommand.py:108
#, python-format
msgid "Command %(cmd)s failed with code %(code)s and message: %(msg)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:123
msgid "No server configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:127
msgid "No application configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:131
msgid "No host configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:141
#, python-format
msgid ""
"The number of host entries in the database does not match the number of hosts"
" in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:169
#, python-format
msgid ""
"The number of services entries in the database does not match the number of "
"services in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:183
#, python-format
msgid ""
"The number of apps entries in the database does not match the number of apps "
"in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:200
#, python-format
msgid ""
"The number of ventilation entries in the database does not match the number "
"of host and apps. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:227
#, python-format
msgid ""
"%(nb_gens)d generators exist whereas %(nb_apps)d applications have been "
"configured"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:234
#, python-format
msgid "########> Error in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:241
#, python-format
msgid "====> Warning in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:247
#, python-format
msgid "%d errors"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:248
#, python-format
msgid "%d warnings"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:250
#, python-format
msgid ""
"%(nbGenerators)d generators have configured %(nbHosts)d hosts on "
"%(nbServers)d servers."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:252
#, python-format
msgid "%(filesWritten)d files have been generated in %(dirsCreated)d directories"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:166
#, python-format
msgid ""
"Test \"%(test_name)s\" on \"%(host)s\" needs the following arguments: "
"%(args)s (and only those)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:727
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:258
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:115
#, python-format
msgid "Not enough memory to validate %(file)s using schema %(schema)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:734
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:265
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:122
#, python-format
msgid "Invalid XML validation schema %(schema)s found while validating %(file)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:741
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:272
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:129
#, python-format
msgid "XML validation failed (%(file)s with schema %(schema)s)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:746
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:277
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:134
#, python-format
msgid ""
"XML validation failed for file %(file)s, using schema %(schema)s, due to an "
"error. Make sure the permissions are set correctly."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:794
#, python-format
msgid "Invalid ventilation group: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:828
#, python-format
msgid "Invalid weight value for test %(test)s on host %(host)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:873
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:108
#: src/vigilo/vigiconf/loaders/hlservice.py:123
#, python-format
msgid "Invalid group name (%s)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:882
#, python-format
msgid "Invalid weight value for host %(host)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:895
#, python-format
msgid "You must associate host \"%s\" with at least one group."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:356
#, python-format
msgid "Invalid weight value for test %(test)s in template %(tpl)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:378
#, python-format
msgid "Invalid weight value for template %(tpl)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/__init__.py:54
msgid ""
"You are trying remote deployment on the Community edition. This feature is "
"only available in the Enterprise edition. Aborting."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:97
#, python-format
msgid "The %s app group is not listed in appsGroupsByServer"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:117
#, python-format
msgid "Invalid server name: %(servername)s. Available servers: %(servers)s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/base.py:73
msgid "Generators must define the generate_host() method"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/file.py:92
#, python-format
msgid "No such template: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:163
msgid "Can't find the metro server for the RRD-based services"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:175
#, python-format
msgid "The metrology server %s must be supervised for the RRD-based services to work"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/map.py:89
#, python-format
msgid "The map group %s has not been added by the install procedure"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:61
msgid "The 'load' method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:115
msgid "The key attribute must be defined, or the get_key() method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:99
msgid "An XSD schema should be provided for validation."
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:102
#, python-format
msgid "XSD file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:198
#, python-format
msgid "End tag mismatch error: %(start)s/%(end)s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:205
#, python-format
msgid "Syntax error in \"%(path)s\": %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:371
#, python-format
msgid "Can't find an item matching %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/local.py:46
#, python-format
msgid "Can't deploy the tar archive for server %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:50
#, python-format
msgid "Cannot find SSH config file: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:87
#, python-format
msgid "The archive file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:93
#, python-format
msgid "Can't copy the configuration archive to %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:108
#, python-format
msgid "Can't deploy the configuration for server %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:78
#, python-format
msgid "Can't find application %s in database"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:167
#, python-format
msgid ""
"Could not determine how to ventilate host \"%s\". Affect some groups to this "
"host or use the ventilation attribute."
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:173
#, python-format
msgid ""
"Found multiple candidates for ventilation (%(candidates)r) on \"%(host)s\", "
"use the ventilation attribute to select one."
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:202
#: src/vigilo/vigiconf/lib/ventilation/remote.py:323
#: src/vigilo/vigiconf/lib/ventilation/remote.py:340
#, python-format
msgid "The Vigilo server %s does not exist"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:270
#, python-format
msgid ""
"No server available for the appgroup %(appgroup)s and the hostgroup "
"%(hostgroup)s, skipping it"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:326
#, python-format
msgid "The Vigilo server %s is already disabled"
msgstr ""

#: src/vigilo/vigiconf/lib/ventilation/remote.py:343
#, python-format
msgid "The Vigilo server %s is already enabled"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:113
#, python-format
msgid "Invalid operator \"%(operator)s\". Possible values: %(possibilities)s"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:141
#, python-format
msgid "Service group %s does not exist."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:70
#, python-format
msgid "Deleting leftover config file from database: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:126
#, python-format
msgid "Loading host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:178
msgid "Cleaning up old hosts"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:220
#, python-format
msgid "Unknown group \"%(group)s\" in host \"%(host)s\"."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:247
#, python-format
msgid ""
"syntax error in host %(host)s: could not find a group matching path "
"\"%(path)s\""
msgstr ""

#: src/vigilo/vigiconf/loaders/topology.py:94
#, python-format
msgid "Not a Dependency: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/topology.py:107
msgid "No dependent supervised item"
msgstr ""

