# Translations template for vigilo-vigiconf.
# Copyright (C) 2017 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2017.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf 4.1.0\n"
"Report-Msgid-Bugs-To: contact.vigilo@c-s.fr\n"
"POT-Creation-Date: 2017-10-30 17:20+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/vigiconf/commandline.py:57
#, python-format
msgid "%(option)s has been deprecated. Please use --stop-after=%(value)s instead."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:87
#, python-format
msgid "ERROR: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:90
msgid "No server to manage."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:135
msgid "Available host classes:"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:145
#, python-format
msgid "No such host class '%s'"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:154
#, python-format
msgid "Tests for host class '%s':"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:194
msgid "Debug mode."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:196
msgid "Don't try to switch to the correct user."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:201
msgid "Vigilo configuration manager"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:202
msgid "Subcommands"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:208
msgid "Prints a summary of the current configuration."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:211
msgid "Supervision servers to query, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:218
msgid "Lists tests available for certain host classes."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:220
msgid "Host classes to query."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:264
msgid "Deploys the configuration on each server if the configuration has changed."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:270
msgid ""
"[DEPRECATED] Stop the process after the file generation, before pushing the "
"files."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:276
msgid ""
"[DEPRECATED] Stop after pushing the files to the remote servers, before "
"services are restarted."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:281
msgid "OPERATION"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:282
#, python-format
msgid "Stop after the given OPERATION (one of '%s')"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:285
msgid "Deploy the given revision"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:290
msgid ""
"Force the given operations. This can be used to return VigiConf to a known "
"good state."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:294
msgid "Simulate only, no copy will actually be made, no commit in the database."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:298
msgid "Disable generators marked as requiring only the database to operate (dbonly)."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:301
msgid "Supervision servers to deploy to, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:308
msgid "Discover the services available on a remote server."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:313
msgid "Output file. Default: standard output."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:315
#, python-format
msgid "SNMP community. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:317
#, python-format
msgid "SNMP version. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:319
#, python-format
msgid "Main group. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:321
msgid "Tests to check."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:323
msgid ""
"Hosts or files to scan. The files must be the result of an snmpwalk command "
"on the '.1' OID with the '-OnQe' options."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:331
msgid "Enables or disables a Vigilo server"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:334
msgid "Don't re-deploy the configuration, only set the status."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:337
msgid "New status"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:339
msgid "Server name(s) to enable/disable"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:354
#, python-format
msgid "VigiConf was launched as user 'root'. Switching to user '%s' instead."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:359
#, python-format
msgid "Unable to switch to user '%s'. Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:384
#, python-format
msgid "VigiConf was not launched as user '%s'. Aborting."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:419 src/vigilo/vigiconf/commandline.py:421
#, python-format
msgid "VigiConf error: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:425
msgid "VigiConf is done."
msgstr ""

#: src/vigilo/vigiconf/conf.py:98
msgid "Loading XML configuration"
msgstr ""

#: src/vigilo/vigiconf/conf.py:112
msgid "Error loading configuration"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:146
#, python-format
msgid "%s: No such file"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:151
msgid "Can't find the hostname using SNMPv2-MIB::sysName.0"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:155
#, python-format
msgid ""
"Invalid HOSTNAME detected in SNMPv2-MIB::sysName.0: \"%s\" (blank character "
"not allowed)"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:185
msgid "The \"snmpwalk\" command is not installed."
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:189
#, python-format
msgid ""
"SNMP walk command failed with error status %(status)s and message:\n"
"  %(msg)s\n"
"The command was: %(cmd)s"
msgstr ""

#: src/vigilo/vigiconf/applications/connector_metro/generator.py:156
#, python-format
msgid "Unknown RRA template %s"
msgstr ""

#: src/vigilo/vigiconf/applications/vigirrd/generator.py:71
#, python-format
msgid "Some datasources are not on a graph: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:73
#, python-format
msgid ""
"A timeout occured while executing application %(application)s with action "
"%(action)s on the following servers: %(servers)s."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:246
#, python-format
msgid "Can't find the validation script for app %(app)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:420
#, python-format
msgid "%(app)s: validation failed for server '%(server)s': %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:427
#, python-format
msgid "%(app)s : Validation successful for server: %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:449
#, python-format
msgid "%(app)s : Qualification failed on '%(server)s' - REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:458
#, python-format
msgid "%(app)s : Qualification successful on server : %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:473
#, python-format
msgid "Starting %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:476
#, python-format
msgid "Reloading %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:484
#, python-format
msgid "Can't Start %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:493
#, python-format
msgid "%(app)s started on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:495
#, python-format
msgid "%(app)s reloaded on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:508
#, python-format
msgid "Stopping %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:518
#, python-format
msgid "Can't Stop %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:527
#, python-format
msgid "%(app)s stopped on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:572
msgid "Empty list of servers"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:646
#, python-format
msgid ""
"Incoherent configuration: application %(app)s has an entry point named "
"%(epname)s in package %(eppkg)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:651
#, python-format
msgid "Application %s is installed but disabled (see conf.d/general/apps.py)"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:655
#, python-format
msgid "application %s is not unique. Providing modules: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:666
#, python-format
msgid "Application %s has been added to conf.d/general/apps.py, but is not installed"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:681
msgid "validation failed, see above for more information."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:683
msgid "Validation successful"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:697
msgid "qualification failed. See above for more information."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:699
msgid "Qualification successful"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:740
#, python-format
msgid ""
"Next attempt for %(action)s action in %(interval)d second(s) (attempt "
"#%(attempt)d)"
msgstr ""

#: src/vigilo/vigiconf/lib/systemcommand.py:110
#, python-format
msgid "Command \"%(cmd)s\" failed with code %(code)s and message: %(msg)s"
msgstr ""

#: src/vigilo/vigiconf/lib/systemcommand.py:129
#, python-format
msgid "Missing command: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:111
msgid "No server configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:114
msgid "No application configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:117
msgid "No host configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:125
#, python-format
msgid ""
"The number of host entries in the database does not match the number of hosts"
" in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:149
#, python-format
msgid ""
"The number of services entries in the database does not match the number of "
"services in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:163
#, python-format
msgid ""
"The number of apps loaded in the database does not match the number of apps "
"to deploy. Database: %(db)d, to deploy: %(deploy)d. Possible cause: one or "
"more app have no Vigilo server to be deployed on."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:181
#, python-format
msgid ""
"The number of ventilation entries in the database does not match the number "
"of host and apps. Database: %(db)d, should be: %(conf)d. Possible cause: one "
"or more application have no Vigilo server to be deployed on."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:215
#, python-format
msgid ""
"%(nb_gens)d generators exist whereas %(nb_apps)d applications have been "
"configured"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:222
#, python-format
msgid "########> Error in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:229
#, python-format
msgid "====> Warning in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:235
#, python-format
msgid "%d errors"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:236
#, python-format
msgid "%d warnings"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:238
#, python-format
msgid ""
"%(nbGenerators)d generators have configured %(nbHosts)d hosts on "
"%(nbServers)d servers."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:240
#, python-format
msgid "%(filesWritten)d files have been generated in %(dirsCreated)d directories"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:55
#, python-format
msgid "Host '%(host)s' defined in multiple files (%(file1)s and %(file2)s)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:129
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:145
#, python-format
msgid ""
"The \"%(old_attribute)s\" attribute has been deprecated. Please use "
"\"%(replacement)s\" instead."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:144
#, python-format
msgid "In host %(host)s: attribute name %(attribute)s is reserved"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:191
#, python-format
msgid ""
"Test \"%(test_name)s\" on \"%(host)s\" needs the following arguments: "
"%(args)s (and only those)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:516
#, python-format
msgid "host '%(host)s': wrong datasource in graph '%(graph)s': %(ds)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:540
#, python-format
msgid "CDEF name must be ASCII-only: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:729
msgid "Cannot override general configuration."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:739
msgid "oxe_login and oxe_password cannot be empty"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:742
#, python-format
msgid ""
"Value for '%(attr)s' (%(value)s) could not be cast into an integer. Using "
"default value (%(default)d)."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:797
#, python-format
msgid "Cannot add tag \"%(tag)s\" to non-existing service \"%(service)s\""
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:820
#, python-format
msgid ""
"Empty value given for directive %(directive)s with target %(target)s on host "
"%(host)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:888
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:286
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:81
#, python-format
msgid "Invalid XML validation schema %(schema)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:894
#: src/vigilo/vigiconf/lib/confclasses/host.py:914
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:292
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:312
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:87
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:107
#, python-format
msgid ""
"Error reading %(file)s, make sure the permissions are set correctly.Message: "
"%(error)s."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:911
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:309
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:104
#, python-format
msgid "XML syntax error in %(file)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:922
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:320
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:115
#, python-format
msgid "XML validation failed: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:977
#, python-format
msgid "Invalid ventilation group: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:1073
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:108
#, python-format
msgid "Invalid group name (%s)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:1117
#, python-format
msgid ""
"Host '%(host)s' inherits from both the '%(tpl1)s' and '%(tpl2)s' templates "
"(in this order), but '%(tpl1)s' already inherits from '%(tpl2)s'. The "
"templates will be reordered to satisfy dependencies."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:1143
#, python-format
msgid "Unable to load templates for %(host)s. Possible cycle."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:1160
#, python-format
msgid "You must associate host \"%s\" with at least one group."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:1167
#, python-format
msgid "Can't add test %(testname)s to host %(hostname)s. Maybe a missing host class ?"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:277
msgid "A cycle has been detected in templates"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:460
#, python-format
msgid "Can't add template \"%(template)s\" to host \"%(hostname)s\": no such template"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:496
#, python-format
msgid ""
"Can't add test %(testname)s to host %(hostname)s (added by template "
"%(tplname)s). Maybe a missing host class ?"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/test.py:301
#, python-format
msgid "Invalid entry point %(epname)s in package %(eppkg)s: %(epmodname)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/test.py:352
#, python-format
msgid "Invalid hostclass \"%s\". Missing __init__.py?"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/test.py:364
#: src/vigilo/vigiconf/lib/confclasses/test.py:397
#: src/vigilo/vigiconf/lib/confclasses/test.py:537
#, python-format
msgid "Unable to load %(file)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/base.py:94
msgid "Generation failed!"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/base.py:97
msgid "Generation successful"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/base.py:128
msgid "Database commit successful"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/base.py:132
msgid "Database commit failed"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/base.py:143
msgid "All servers are up-to-date. No restart needed."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/base.py:158
#, python-format
msgid "Current revision in the repository : %d"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/base.py:167
#, python-format
msgid "Cannot get revision for server: %(server)s. REASON : %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/factory.py:35
msgid ""
"You are attempting a remote deployment on the Community edition. This feature"
" is only available in the Enterprise edition. Aborting."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/local.py:28
msgid ""
"Vigilo server management is only available in the Enterprise edition. "
"Aborting."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:55
msgid ""
"you can't go back to a former revision if you have modified your "
"configuration. Use 'svn revert' to cancel your modifications"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:91
#, python-format
msgid "can't compute SVN differences for the configuration dir: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:118
msgid "Not updating because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:129
#, python-format
msgid "can't get SVN status for the configuration dir: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:193
#, python-format
msgid "Can't add %(path)s in repository: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:216
#, python-format
msgid "can't remove %(path)s from repository: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:227
msgid "Not committing because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:239
#, python-format
msgid "can't commit the configuration dir in SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:244
msgid "SVN commit successful"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:269
#, python-format
msgid ""
"can't execute the request to update the local copy. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:309
#, python-format
msgid "can't execute the request to get the current revision: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/base.py:69
msgid "Generators must define the generate_host() method"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/file.py:81
#, python-format
msgid "No such template: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:87
#: src/vigilo/vigiconf/lib/generators/manager.py:166
#: src/vigilo/vigiconf/lib/generators/manager.py:219
#, python-format
msgid "Skipping %s generator"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:90
#: src/vigilo/vigiconf/lib/generators/manager.py:223
#, python-format
msgid "Generated configuration for %s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:124
msgid "Computing ventilation"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:137
msgid "Running generators"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:159
#, python-format
msgid "Generating configuration for %s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:171
msgid "Running database generators"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/manager.py:185
#, python-format
msgid "%(errtype)s in application %(app)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:47
msgid "The 'load' method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:101
msgid "The key attribute must be defined, or the get_key() method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:119
#: src/vigilo/vigiconf/lib/loaders/dbloader.py:176
#, python-format
msgid "Trying to override configuration for already-defined entity \"%(entity)s\""
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:76
#, python-format
msgid "XSD file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:166
#, python-format
msgid "End tag mismatch error: %(start)s/%(end)s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:173
#, python-format
msgid "Syntax error in \"%(path)s\": %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:348
#, python-format
msgid "Can't find an item matching %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:127
#, python-format
msgid ""
"Can't activate the configuration on %(server)s. COMMAND \"%(cmd)s\" FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:147
#, python-format
msgid "Can't tar config for server %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:162
#, python-format
msgid "%s : deployment successful."
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:179
#, python-format
msgid "Cannot copy files (%(from)s to %(to)s): %(error)s."
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:242
#, python-format
msgid "Cannot write the revision file: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:247
#, python-format
msgid ""
"Server %(server)s:\n"
"    deployed: %(deployed)d\n"
"    installed: %(installed)d\n"
"    previous: %(previous)d"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:260
msgid "should be deployed"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:262
msgid "should restart"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:265
msgid "disabled"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:270
#, python-format
msgid "Server %s cannot be disabled"
msgstr ""

#: src/vigilo/vigiconf/lib/server/base.py:272
#, python-format
msgid "Server %s cannot be enabled"
msgstr ""

#: src/vigilo/vigiconf/lib/server/factory.py:118
msgid "On the Community Edition, you can only use localhost"
msgstr ""

#: src/vigilo/vigiconf/lib/server/factory.py:132
msgid ""
"Remote server management is not possible with the Community edition. This "
"feature is only available in the Enterprise edition. Aborting."
msgstr ""

#: src/vigilo/vigiconf/lib/server/local.py:51
#, python-format
msgid "Can't deploy the tar archive for server %(server)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server/manager.py:114
msgid "All servers are up-to-date, no deployment needed."
msgstr ""

#: src/vigilo/vigiconf/lib/server/manager.py:120
msgid ""
"The configurations files have not been transfered on every server. See above "
"for more information."
msgstr ""

#: src/vigilo/vigiconf/lib/server/manager.py:138
msgid "The revision has not been set on every server. See above for more information."
msgstr ""

#: src/vigilo/vigiconf/lib/server/manager.py:153
msgid "Switch directories was not successful on each server."
msgstr ""

#: src/vigilo/vigiconf/loaders/application.py:29
msgid "Loading applications"
msgstr ""

#: src/vigilo/vigiconf/loaders/application.py:33
msgid "Done loading applications"
msgstr ""

#: src/vigilo/vigiconf/loaders/graphgroup.py:30
msgid "Loading graph groups"
msgstr ""

#: src/vigilo/vigiconf/loaders/graphgroup.py:37
msgid "Done loading graph groups"
msgstr ""

#: src/vigilo/vigiconf/loaders/group.py:106
msgid "Loading groups"
msgstr ""

#: src/vigilo/vigiconf/loaders/group.py:110
msgid "Done loading groups"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:73
#, python-format
msgid "Deleting leftover config file from database: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:79
msgid "Loading hosts"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:110
#, python-format
msgid "Registering new configuration file '%(relative)s' (from %(absolute)s)"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:137
#, python-format
msgid "Loading host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:410
msgid "Done loading hosts"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:424
#, python-format
msgid "Unknown group \"%(group)s\" in host \"%(host)s\"."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:453 src/vigilo/vigiconf/loaders/host.py:465
#, python-format
msgid ""
"syntax error in host %(host)s: could not find a group matching path "
"\"%(path)s\""
msgstr ""

#: src/vigilo/vigiconf/loaders/ventilation.py:59
msgid "Loading ventilation"
msgstr ""

#: src/vigilo/vigiconf/loaders/ventilation.py:87
#, python-format
msgid "Can't load the ventilation in database: the host %s is not in database yet"
msgstr ""

#: src/vigilo/vigiconf/loaders/ventilation.py:123
#, python-format
msgid ""
"The application %s has been removed from the configuration, it needs to be "
"stopped manually"
msgstr ""

#: src/vigilo/vigiconf/loaders/ventilation.py:134
msgid "Done loading ventilation"
msgstr ""

#: src/vigilo/vigiconf/loaders/vigiloserver.py:42
msgid "Loading Vigilo servers"
msgstr ""

#: src/vigilo/vigiconf/loaders/vigiloserver.py:56
msgid "Done loading Vigilo servers"
msgstr ""

#: src/vigilo/vigiconf/test/test_conf_testfactory.py:93
#: src/vigilo/vigiconf/test/testdata/tests/imports/Error.py:20
msgid "Import test was successful"
msgstr ""

#: src/vigilo/vigiconf/tests/all/Interface.py:91
#: src/vigilo/vigiconf/tests/all/Interface.py:99
#, python-format
msgid "Invalid value \"%(value)s\" for %(param)s. Expected one of: %(candidates)s."
msgstr ""

#: src/vigilo/vigiconf/tests/all/NTP.py:28
msgid "Test NTP has been deprecated. Please use NagiosPlugin instead"
msgstr ""

#: src/vigilo/vigiconf/tests/all/Ping.py:33
#, python-format
msgid "\"%s\" should be a list with two values"
msgstr ""

#: src/vigilo/vigiconf/tests/all/UpTime.py:40
msgid "Invalid thresholds. Expected 0 < crit < warn"
msgstr ""

