# Translations template for vigilo-vigiconf.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2010-07-13 09:30+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/vigiconf/commandline.py:59
#, python-format
msgid "Cannot load the configuration: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:69
#, python-format
msgid "ERROR: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:72
msgid "No server to manage."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:137
msgid "Vigilo configuration manager"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:138
msgid "Debug mode."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:139
msgid "Subcommands"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:146
msgid "Servers to query, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:150
msgid "Application status management."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:154
msgid "Stop the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:156
msgid "Start the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:158
msgid "Restart the applications."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:160
msgid "Applications to manage, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:164
msgid ""
"Deploys the previously installed configuration. 2 consecutives undo will "
"return to the configuration that was installed before the first undo (ie. "
"redo)."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:170
msgid "Do not restart the applications after switching the configuration."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:173
msgid "Servers to undo, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:177
msgid "Deploys the configuration on each server if the configuration has changed."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:181
msgid "Stop the process after the file generation, before pushing the files."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:184
msgid ""
"Stop after pushing the files to the remote servers, and before restarting the"
" services."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:187
msgid "Deploy the given revision"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:189
msgid "Force the immediate execution of the command. Do not wait. Bypass all checks."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:192
msgid "Simulate only, no copy will actually be made, no commit in the database."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:195
msgid "Servers to deploy to, all of them if not specified."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:200
msgid "Discover the services available on a remote server"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:205
msgid "Output file. Default: standard output."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:207
#, python-format
msgid "SNMP community. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:209
#, python-format
msgid "SNMP version. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:211
#, python-format
msgid "Main group. Default: %(default)s."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:213
msgid ""
"Hosts or files to scan. The files must be the result of an snmpwalk command "
"on the '.1' OID with the '-OnQ' options."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:222
msgid "VigiConf starting..."
msgstr ""

#: src/vigilo/vigiconf/commandline.py:227
#, python-format
msgid "Can't obtain lock on lockfile. Dispatchator already running ? REASON : %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:236 src/vigilo/vigiconf/commandline.py:238
#, python-format
msgid "VigiConf error: %s"
msgstr ""

#: src/vigilo/vigiconf/commandline.py:241
msgid "VigiConf ended."
msgstr ""

#: src/vigilo/vigiconf/conf.py:298
#, python-format
msgid "Error loading configuration file %(file)s: %(error)s"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:76
#, python-format
msgid "%s: No such file"
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:117
msgid "The \"snmpwalk\" command is not installed."
msgstr ""

#: src/vigilo/vigiconf/discoverator.py:120
#, python-format
msgid ""
"SNMP walk command failed with error status %(status)s and message:\n"
"%(msg)s\n"
"The command was: %(cmd)sstatus"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:225
#, python-format
msgid "Unknown application: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:286
msgid "Can't generate configuration"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:292
msgid "Validation Successful"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:295
msgid "Commit Successful"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:306
msgid ""
"You can't go back to a former revision if you have modified your "
"configuration. Use 'svn revert' to cancel your modifications"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:320
#, python-format
msgid "Can't get the SVN status for the configuration dir: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:336
msgid "Not updating because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:348
#, python-format
msgid "Adding new conf file in SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:356
#, python-format
msgid "Can't add %s in SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:361
#, python-format
msgid "Removing old conf file from SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:369
#, python-format
msgid "Can't remove %s from SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:375
msgid "Not committing because the 'svnrepository' configuration parameter is empty"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:387
#, python-format
msgid "Can't commit the configuration dir in SVN: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:402
#, python-format
msgid ""
"Can't execute the request to update the local copy. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:444
#, python-format
msgid "Can't execute the request to get the current revision: %s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:516
msgid ""
"The configurations files have not been transfered on every server. See above "
"for more information."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:558
msgid "All servers are up-to-date. Nothing to do."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:674
msgid "Switch directories was not successful on each server."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:699
#, python-format
msgid "Server %s should be deployed."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:701
msgid "All servers are up-to-date. No restart needed."
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:732
msgid "Stop applications failed"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:749
msgid "Start applications failed"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:764
#, python-format
msgid "Current revision in the repository : %d"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:772
msgid "(should be deployed)"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:774
msgid "(should restart)"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:775
#, python-format
msgid "Revisions for server %(server)s : %(rev)s%(dep)s%(restart)s"
msgstr ""

#: src/vigilo/vigiconf/dispatchator.py:780
#, python-format
msgid "Cannot get revision for server: %(server)s. REASON : %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:209
#, python-format
msgid "Using existing MapGroup for group %s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:212
#, python-format
msgid "Creating MapGroup for group %s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:219
#, python-format
msgid "Using existing Map for group %s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:222
#, python-format
msgid "Creating Map for SupItemGroup %(group)s in MapGroup %(mapgroup)s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:233
#, python-format
msgid "Removing MapGroup %s and its children"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:286
#, python-format
msgid "Removing Map for group %s"
msgstr ""

#: src/vigilo/vigiconf/generators/groups_maps.py:305
msgid "Generating maps for the host groups"
msgstr ""

#: src/vigilo/vigiconf/generators/nagios_hls.py:75
msgid "No server has been configured to host High-Level Services"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:193
#, python-format
msgid "Can't find the appgroup for app %s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:258
#, python-format
msgid "%(appname)s: validation failed for server '%(servername)s': %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:265
#, python-format
msgid "%(app)s : Validation successful for server: %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:313
#, python-format
msgid "%s : Qualification failed on : %s - "
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:318
#, python-format
msgid "%(app)s : Qualification successful on server : %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:362
#: src/vigilo/vigiconf/lib/application.py:386
#, python-format
msgid "%s : Start process failed."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:397
#, python-format
msgid "Starting %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:406
#, python-format
msgid "Can't Start %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:413
#, python-format
msgid "%(app)s started on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:453
#: src/vigilo/vigiconf/lib/application.py:477
#, python-format
msgid "%s : Stop process failed."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:488
#, python-format
msgid "Stopping %(app)s on %(server)s ..."
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:497
#, python-format
msgid "Can't Stop %(app)s on %(server)s - REASON %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/application.py:504
#, python-format
msgid "%(app)s stopped on %(server)s"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:61
msgid "The 'load' method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:115
msgid "The key attribute must be defined, or the get_key() method must be redefined"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:128
#, python-format
msgid "Updating: %(key)s (%(class)s)"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:140
#: src/vigilo/vigiconf/loaders/graphgroup.py:62
#: src/vigilo/vigiconf/loaders/group.py:106
#, python-format
msgid "Inserting: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/dbloader.py:147
#, python-format
msgid "Deleting: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:117
msgid "Server name set to None."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:119
msgid "Server name incorrect (length = 0)."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:178
msgid "Unknown command type."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:211
#: src/vigilo/vigiconf/lib/remotecommand.py:244
msgid "Cannot reach server."
msgstr ""

#: src/vigilo/vigiconf/lib/remotecommand.py:214
#: src/vigilo/vigiconf/lib/remotecommand.py:246
msgid "Cannot find file."
msgstr ""

#: src/vigilo/vigiconf/lib/revisionmanager.py:174
#, python-format
msgid "Cannot write the revision file: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:80
msgid "On the Community Edition, you can only use localhost"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:184
#, python-format
msgid "Can't refactor server. COMMAND %(cmd) FAILED. REASON: %(reason)s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:208
#, python-format
msgid "Can't deploy server. REASON: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:210
#, python-format
msgid "%s : deployement successful."
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:224
#, python-format
msgid "Cannot copy files (%(from)s to %(to)s): %(error)s."
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:266
#, python-format
msgid "UNDO can't be done. Directory 'old' does not exist on %s."
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:270 src/vigilo/vigiconf/lib/server.py:290
#, python-format
msgid "UNDO can't be done. %s"
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:285
#, python-format
msgid "UNDO failed on %s."
msgstr ""

#: src/vigilo/vigiconf/lib/server.py:288
#, python-format
msgid "UNDO successful on %s."
msgstr ""

#: src/vigilo/vigiconf/lib/systemcommand.py:108
#, python-format
msgid "Command %(cmd)s failed with code %(code)s and message: %(msg)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:113
msgid "No server configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:117
msgid "No application configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:121
msgid "No host configuration to be generated"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:144
#, python-format
msgid ""
"%(nb_gens)d generators exist whereas %(nb_apps)d applications have been "
"configured"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:152
#, python-format
msgid "########> Error in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:159
#, python-format
msgid "====> Warning in %(source)s (object %(object)s): %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:165
#, python-format
msgid "%d errors"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:166
#, python-format
msgid "%d warnings"
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:168
#, python-format
msgid ""
"%(nbGenerators)d generators have configured%(nbHosts)d hosts on %(nbServers)d"
" servers."
msgstr ""

#: src/vigilo/vigiconf/lib/validator.py:170
#, python-format
msgid "%(filesWritten)d files have been generated in %(dirsCreated)d directories"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:95
msgid "An XSD schema should be provided for validation."
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:97
#, python-format
msgid "XSD file does not exist: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:106
#, python-format
msgid "XML validation failed (%(file)s with schema %(schema)s)"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:168
#, python-format
msgid "End tag mismatch error: %(start)s/%(end)s"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:175
#, python-format
msgid "Syntax error in \"%(path)s\": %(error)s"
msgstr ""

#: src/vigilo/vigiconf/lib/xmlloader.py:319
#: src/vigilo/vigiconf/lib/confclasses/host.py:628
#, python-format
msgid "Sucessfully parsed %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:149
#, python-format
msgid ""
"Test \"%(test_name)s\" on \"%(host)s\" needs the following arguments: "
"%(args)s (and only those)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:653
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:245
msgid "XML validation failed"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:686
#, python-format
msgid "Invalid ventilation group: %s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:696
#, python-format
msgid "Invalid weight: %r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:746
#, python-format
msgid "Invalid weight value for test %(test)s on host %(host)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:779
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:102
#, python-format
msgid "Invalid group name (%s)"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:787
#, python-format
msgid "You must associate host \"%s\" with at least one group."
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/host.py:790
#, python-format
msgid "Loaded host %(host)s, address %(address)s"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:307
#, python-format
msgid "Invalid weight value for test %(test)s in template %(tpl)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:327
#, python-format
msgid "Invalid weight value for template %(tpl)s: %(weight)r"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/__init__.py:49
msgid ""
"You are trying remote deployment on the Community edition. This feature is "
"only available in the Enterprise edition. Aborting."
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:100
#, python-format
msgid "The %s app group is not listed in appsGroupsByServer"
msgstr ""

#: src/vigilo/vigiconf/lib/dispatchmodes/remote.py:127
#, python-format
msgid "Invalid server name: %(servername)s. Available servers: %(servers)s"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/__init__.py:52
msgid "Generators must define the generate() method"
msgstr ""

#: src/vigilo/vigiconf/lib/generators/map.py:86
#, python-format
msgid "The map group %s has not been added by the install procedure"
msgstr ""

#: src/vigilo/vigiconf/lib/servertypes/remote.py:50
#, python-format
msgid "Cannot find SSH config file: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/dependency.py:61
#, python-format
msgid "Not a Dependency: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/dependency.py:106
msgid "No dependent supitem"
msgstr ""

#: src/vigilo/vigiconf/loaders/dependency.py:108
#, python-format
msgid "Creating dependency from %(from)s to %(to)s"
msgstr ""

#: src/vigilo/vigiconf/loaders/dependency.py:130
#, python-format
msgid "Can't find an item matching %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/hlservice.py:85
#, python-format
msgid "Service group %s does not exist."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:61
#, python-format
msgid "Loading host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:75
#, python-format
msgid "Loading groups for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:79
#, python-format
msgid "Loading services for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:84
#, python-format
msgid "Loading nagios conf for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:89
#, python-format
msgid "Loading perfdatasources for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:94
#, python-format
msgid "Loading graphs for host %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:99
msgid "Cleaning up old graphs and graphgroups"
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:119
#, python-format
msgid "Unknown group \"%(group)s\" in host \"%(host)s\"."
msgstr ""

#: src/vigilo/vigiconf/loaders/host.py:148
#, python-format
msgid "Could not find a group matching this path: %s"
msgstr ""

#: src/vigilo/vigiconf/loaders/map.py:87 src/vigilo/vigiconf/loaders/map.py:123
#, python-format
msgid "Unknown tag: <%s>"
msgstr ""

#: src/vigilo/vigiconf/loaders/map.py:156 src/vigilo/vigiconf/loaders/map.py:169
msgid "Host node must be in a nodes block."
msgstr ""

#: src/vigilo/vigiconf/loaders/map.py:162
#, python-format
msgid "Host %s does not exist"
msgstr ""

