# French translations for vigilo-vigiconf.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2010-07-12 15:40+0200\n"
"PO-Revision-Date: 2011-03-22 10:39+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: fr <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/vigiconf/commandline.py:70
#, python-format
msgid "ERROR: %s"
msgstr "ERREUR : %s"

#: src/vigilo/vigiconf/commandline.py:73
msgid "No server to manage."
msgstr "Aucun serveur à gérer."

#: src/vigilo/vigiconf/commandline.py:140
msgid "usage: "
msgstr "usage : "

#: src/vigilo/vigiconf/commandline.py:141
#, python-format
msgid "conflicting option string(s): %s"
msgstr "conflit entre chaine(s) d'option : %s"

#: src/vigilo/vigiconf/commandline.py:142
msgid "subcommands"
msgstr "sous-commandes"

#: src/vigilo/vigiconf/commandline.py:143
#, python-format
msgid "unrecognized arguments: %s"
msgstr "arguments non reconnus : %s"

#: src/vigilo/vigiconf/commandline.py:144
msgid "expected one argument"
msgstr "un argument attendu"

#: src/vigilo/vigiconf/commandline.py:145
msgid "expected at most one argument"
msgstr "au plus un argument attendu"

#: src/vigilo/vigiconf/commandline.py:146
msgid "expected at least one argument"
msgstr "au moins un argument attendu"

#: src/vigilo/vigiconf/commandline.py:147
#, python-format
msgid "expected %s argument(s)"
msgstr "%s argument(s) attendu(s)"

#: src/vigilo/vigiconf/commandline.py:148
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr "choix incorrect : %r (choisissez parmis %s)"

#: src/vigilo/vigiconf/commandline.py:149
msgid "positional arguments"
msgstr "arguments positionnels"

#: src/vigilo/vigiconf/commandline.py:150
msgid "optional arguments"
msgstr "arguments optionnels"

#: src/vigilo/vigiconf/commandline.py:151
msgid "too few arguments"
msgstr "pas assez d'arguments"

#: src/vigilo/vigiconf/commandline.py:152
#, python-format
msgid "argument %s is required"
msgstr "l'arguments %s est nécessaire"

#: src/vigilo/vigiconf/commandline.py:153
#, python-format
msgid "one of the arguments %s is required"
msgstr "l'une des arguments %s est nécessaire"

#: src/vigilo/vigiconf/commandline.py:154
#, python-format
msgid "%s: error: %s\n"
msgstr "%s : erreur : %s\n"

#: src/vigilo/vigiconf/commandline.py:155
msgid "show this help message and exit"
msgstr "affiche ce message d'aide et quitte"

#: src/vigilo/vigiconf/commandline.py:156
msgid "show program's version number and exit"
msgstr "affiche le numéro de version du programme et quitte"

#: src/vigilo/vigiconf/commandline.py:160
msgid "Debug mode."
msgstr "Mode de débogage"

#: src/vigilo/vigiconf/commandline.py:162
msgid "Don't try to switch to the correct user."
msgstr "Ne pas tenter de basculer vers le bon compte utilisateur."

#: src/vigilo/vigiconf/commandline.py:167
msgid "Vigilo configuration manager"
msgstr "Gestionnaire de configuration Vigilo"

#: src/vigilo/vigiconf/commandline.py:168
msgid "Subcommands"
msgstr "Sous-commandes"

#: src/vigilo/vigiconf/commandline.py:174
msgid "Prints a summary of the current configuration."
msgstr "Affiche un résumé de la configuration actuelle."

#: src/vigilo/vigiconf/commandline.py:177
msgid "Supervision servers to query, all of them if not specified."
msgstr "Serveurs de supervision à interroger; tous si aucun n'est donné."

#: src/vigilo/vigiconf/commandline.py:221
msgid "Deploys the configuration on each server if the configuration has changed."
msgstr "Déploie la configuration sur chaque serveur si la configuration a changé."

#: src/vigilo/vigiconf/commandline.py:225
msgid "Stop the process after the file generation, before pushing the files."
msgstr ""
"Arrêter le processus après la génération des fichiers et avant l'envoi "
"des fichiers."

#: src/vigilo/vigiconf/commandline.py:228
msgid ""
"Stop after pushing the files to the remote servers, and before restarting"
" the services."
msgstr ""
"Arrêter après l'envoi des fichiers aux serveurs distants et avant le "
"redémarrage des services."

#: src/vigilo/vigiconf/commandline.py:231
msgid "Deploy the given revision"
msgstr "Déployer la révision donnée"

#: src/vigilo/vigiconf/commandline.py:233
msgid ""
"Force the immediate execution of the command. Do not wait. Bypass all "
"checks."
msgstr ""
"Forcer l'exécution immédiate de la commande. Pas d'attente. Ne pas "
"effectuer les vérifications."

#: src/vigilo/vigiconf/commandline.py:236
msgid "Simulate only, no copy will actually be made, no commit in the database."
msgstr ""
"Simuler uniquement. Aucune copie n'a lieu, la base de données n'est pas "
"modifiée."

#: src/vigilo/vigiconf/commandline.py:239
msgid "Supervision servers to deploy to, all of them if not specified."
msgstr "Serveurs de supervision vers lesquels déployer; tous si aucun n'est donné."

#: src/vigilo/vigiconf/commandline.py:246
msgid "Discover the services available on a remote server."
msgstr "Découvrir les services disponibles sur un serveur distant."

#: src/vigilo/vigiconf/commandline.py:251
msgid "Output file. Default: standard output."
msgstr "Fichier destination. Par défaut, la sortie standard est utilisée."

#: src/vigilo/vigiconf/commandline.py:253
#, python-format
msgid "SNMP community. Default: %(default)s."
msgstr "Communauté SNMP. Par défaut : %(default)s"

#: src/vigilo/vigiconf/commandline.py:255
#, python-format
msgid "SNMP version. Default: %(default)s."
msgstr "Version de SNMP. Par défaut : %(default)s."

#: src/vigilo/vigiconf/commandline.py:257
#, python-format
msgid "Main group. Default: %(default)s."
msgstr "Groupe principal. Par défaut : %(default)s."

#: src/vigilo/vigiconf/commandline.py:259
msgid ""
"Hosts or files to scan. The files must be the result of an snmpwalk "
"command on the '.1' OID with the '-OnQe' options."
msgstr ""
"Hôtes ou fichiers à scanner. Les fichiers doivent être le résultat d'une "
"commande snmpwalk sur l'OID '.1' avec les options '-OnQe'."

#: src/vigilo/vigiconf/commandline.py:267
msgid "Enables or disables a Vigilo server"
msgstr "Active ou désactive un serveur Vigilo."

#: src/vigilo/vigiconf/commandline.py:270
msgid "Don't re-deploy the configuration, only set the status."
msgstr "Ne pas redéployer la configuration, mettre juste à jour le statut."

#: src/vigilo/vigiconf/commandline.py:273
msgid "New status"
msgstr "Nouveau statut"

#: src/vigilo/vigiconf/commandline.py:275
msgid "Server name(s) to enable/disable"
msgstr "Nom du/des serveurs à activer/désactiver."

#: src/vigilo/vigiconf/commandline.py:286
msgid ""
"VigiConf was launched as user 'root'. Switching to user 'vigiconf' "
"instead."
msgstr ""
"VigiConf a été lancé depuis le compte 'root'. Utilisation du compte "
"'vigiconf' à la place."

#: src/vigilo/vigiconf/commandline.py:291
msgid "Unable to switch to user 'vigiconf'. Aborting."
msgstr "Impossible de basculer vers le compte 'vigiconf'. Abandon."

#: src/vigilo/vigiconf/commandline.py:315
msgid "VigiConf was not launched as user 'vigiconf'. Aborting."
msgstr "VigiConf n'a pas été lancé en utilisant le compte 'vigiconf'. Abandon."

#: src/vigilo/vigiconf/commandline.py:348
#, python-format
msgid ""
"Can't obtain lock on lockfile (%(lockfile)s). VigiConf already running ? "
"REASON : %(error)s"
msgstr ""
"Impossible d'obtenir un verrou sur le fichier %(lockfile)s. VigiConf est-"
"il déjà lancé ? Raison : %(error)s"

#: src/vigilo/vigiconf/commandline.py:361
#: src/vigilo/vigiconf/commandline.py:363
#, python-format
msgid "VigiConf error: %s"
msgstr "Erreur dans VigiConf : %s"

#: src/vigilo/vigiconf/commandline.py:367
msgid "VigiConf is done."
msgstr "VigiConf se termine"

#: src/vigilo/vigiconf/conf.py:74
msgid "Loading XML configuration"
msgstr "Chargement de la configuration XML"

#: src/vigilo/vigiconf/conf.py:79
msgid "Error loading configuration"
msgstr "Impossible de charger la configuration"

#: src/vigilo/vigiconf/discoverator.py:78
#, python-format
msgid "%s: No such file"
msgstr "%s : Fichier non trouvé"

#: src/vigilo/vigiconf/discoverator.py:90
#, python-format
msgid ""
"Invalid HOSTNAME detected in SNMPv2-MIB::sysName.0: \"%s\" (blank "
"character not allowed)"
msgstr ""
"HOSTNAME invalide dans SNMPv2-MIB::sysName.0: \"%s\" (caractères blancs "
"non autorisés)"

#: src/vigilo/vigiconf/discoverator.py:127
msgid "The \"snmpwalk\" command is not installed."
msgstr "La commande \"snmpwalk\" n'est pas installée."

#: src/vigilo/vigiconf/discoverator.py:130
#, python-format
msgid ""
"SNMP walk command failed with error status %(status)s and message:\n"
"%(msg)s\n"
"The command was: %(cmd)s"
msgstr ""
"La commande SNMP walk a échoué avec le statut %(status)s et ce message :\n"
"%(msg)s\n"
"La commande était : %(cmd)s"

#: src/vigilo/vigiconf/applications/nagios_hls/generator.py:70
msgid "No server has been configured to host High-Level Services"
msgstr "Aucun serveur n'a été configuré pour héberger les Services de Haut Niveau"

#: src/vigilo/vigiconf/applications/vigirrd/generator.py:83
#, python-format
msgid "Some datasources are not on a graph: %s"
msgstr "Certains indicateurs ne sont pas présents sur un graphe: %s"

#: src/vigilo/vigiconf/connector/command.py:26
msgid "An instance of Command can only be run once"
msgstr "Une instance d'une commande ne peut être exécutée qu'une seule fois"

#: src/vigilo/vigiconf/connector/command.py:94
#, python-format
msgid "VigiConf finished properly (duration: %ds)"
msgstr "VigiConf s'est correctement terminée (durée : %d secondes)"

#: src/vigilo/vigiconf/connector/command.py:99
#, python-format
msgid "VigiConf failed ! Exit code: %(rcode)d, duration: %(duration)ds"
msgstr ""
"VigiConf a échoué ! Code d'erreur : %(rcode)d, durée : %(duration)d "
"secondes"

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:41
#, python-format
msgid "Received unhandled message type: %(msgtype)s"
msgstr "Réception d'un type de message non-reconnu : %(msgtype)s"

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:71
#, python-format
msgid "Running command: %s"
msgstr "Exécution de la commande : %s"

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:77
msgid "FAILED!"
msgstr "ÉCHEC !"

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:80
msgid "OK."
msgstr "OK."

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:81
#, python-format
msgid "Duration: %d seconds"
msgstr "Durée : %d secondes"

#: src/vigilo/vigiconf/connector/xmpptovigiconf.py:151
#, python-format
msgid "Accepting subscription request from %s"
msgstr "Autorisation de la demande de souscription de %s"

#: src/vigilo/vigiconf/lib/application.py:227
#, python-format
msgid "Can't find the validation script for app %(app)s: %(error)s"
msgstr ""
"Impossible de trouver le script de validation pour l'application %(app)s "
": %(error)s"

#: src/vigilo/vigiconf/lib/application.py:387
#, python-format
msgid "%(app)s: validation failed for server '%(server)s': %(reason)s"
msgstr "%(app)s : échec de la validation pour le serveur '%(server)s' : %(reason)s"

#: src/vigilo/vigiconf/lib/application.py:394
#, python-format
msgid "%(app)s : Validation successful for server: %(server)s"
msgstr "%(app)s : validation réussie pour le serveur %(server)s"

#: src/vigilo/vigiconf/lib/application.py:416
#, python-format
msgid "%(app)s : Qualification failed on '%(server)s' - REASON: %(reason)s"
msgstr "%(app)s : échec de la qualification sur '%(server)s' - RAISON : %(reason)s"

#: src/vigilo/vigiconf/lib/application.py:425
#, python-format
msgid "%(app)s : Qualification successful on server : %(server)s"
msgstr "%(app)s : qualification réussie sur le serveur %(server)s"

#: src/vigilo/vigiconf/lib/application.py:439
#, python-format
msgid "Starting %(app)s on %(server)s ..."
msgstr "Démarrage de %(app)s sur le serveur %(server)s ..."

#: src/vigilo/vigiconf/lib/application.py:449
#, python-format
msgid "Can't Start %(app)s on %(server)s - REASON %(reason)s"
msgstr "Impossible de démarrer %(app)s sur %(server)s - RAISON %(reason)s"

#: src/vigilo/vigiconf/lib/application.py:457
#, python-format
msgid "%(app)s started on %(server)s"
msgstr "%(app)s démarré sur %(server)s"

#: src/vigilo/vigiconf/lib/application.py:472
#, python-format
msgid "Stopping %(app)s on %(server)s ..."
msgstr "Arrêt de %(app)s sur %(server)s ..."

#: src/vigilo/vigiconf/lib/application.py:482
#, python-format
msgid "Can't Stop %(app)s on %(server)s - REASON %(reason)s"
msgstr "Impossible d'arrêter %(app)s sur %(server)s  - RAISON %(reason)s"

#: src/vigilo/vigiconf/lib/application.py:490
#, python-format
msgid "%(app)s stopped on %(server)s"
msgstr "%(app)s arrêté sur %(server)s"

#: src/vigilo/vigiconf/lib/application.py:551
#, python-format
msgid ""
"Incoherent configuration: application %(app)s has an entry point named "
"%(epname)s in package %(eppkg)s"
msgstr ""
"Configuration incohérente : le point d'entrée de l'application %(app)s "
"s'appelle %(epname)s dans le paquet %(eppkg)s"

#: src/vigilo/vigiconf/lib/application.py:556
#, python-format
msgid "Application %s is installed but disabled (see conf.d/general/apps.py)"
msgstr ""
"L'application %s est installée mais elle est désactivée (voir "
"conf.d/general/apps.py)"

#: src/vigilo/vigiconf/lib/application.py:560
#, python-format
msgid "application %s is not unique."
msgstr "le nom d'application %s n'est pas unique."

#: src/vigilo/vigiconf/lib/application.py:561
#, python-format
msgid " Providing modules: %s"
msgstr " Modules fournisseurs : %s"

#: src/vigilo/vigiconf/lib/application.py:569
#, python-format
msgid ""
"Application %s has been added to conf.d/general/apps.py, but is not "
"installed"
msgstr ""
"L'application %s a été ajoutée dans conf.d/general/apps.py, mais elle "
"n'est pas installée"

#: src/vigilo/vigiconf/lib/application.py:584
msgid "validation failed, see above for more information."
msgstr ""
"échec de la validation, voir les messages ci-dessus pour plus "
"d'information."

#: src/vigilo/vigiconf/lib/application.py:586
msgid "Validation successful"
msgstr "Validation réussie"

#: src/vigilo/vigiconf/lib/application.py:600
msgid "qualification failed. See above for more information."
msgstr ""
"échec de la qulification. Lire les messages ci-dessus pour plus "
"d'information."

#: src/vigilo/vigiconf/lib/application.py:602
msgid "Qualification successful"
msgstr "Qualification réussie"

#: src/vigilo/vigiconf/lib/remotecommand.py:116
msgid "Server name set to None"
msgstr "Nom de serveur positionné à None."

#: src/vigilo/vigiconf/lib/remotecommand.py:119
msgid "Invalid server name (empty)"
msgstr "Nom de serveur non valide (vide)"

#: src/vigilo/vigiconf/lib/remotecommand.py:179
msgid "Unknown command type."
msgstr "Type de commande inconnu."

#: src/vigilo/vigiconf/lib/remotecommand.py:196
#, python-format
msgid "The source file does not exist: %s"
msgstr "Le fichier source n'existe pas : %s"

#: src/vigilo/vigiconf/lib/remotecommand.py:214
#: src/vigilo/vigiconf/lib/remotecommand.py:249
msgid "Cannot reach server."
msgstr "Impossible de joindre le serveur."

#: src/vigilo/vigiconf/lib/remotecommand.py:218
#: src/vigilo/vigiconf/lib/remotecommand.py:251
msgid "Cannot find file."
msgstr "Impossible de trouver le fichier."

#: src/vigilo/vigiconf/lib/systemcommand.py:52
#, python-format
msgid "Command \"%(cmd)s\" failed with code %(code)s and message: %(msg)s"
msgstr "La commande %(cmd)s a échoué avec le code %(code)s et ce message : %(msg)s"

#: src/vigilo/vigiconf/lib/validator.py:127
msgid "No server configuration to be generated"
msgstr "Aucune configuration de serveur à générer"

#: src/vigilo/vigiconf/lib/validator.py:130
msgid "No application configuration to be generated"
msgstr "Aucune configuration d'application à générer"

#: src/vigilo/vigiconf/lib/validator.py:133
msgid "No host configuration to be generated"
msgstr "Aucune configuration d'hôte à générer"

#: src/vigilo/vigiconf/lib/validator.py:141
#, python-format
msgid ""
"The number of host entries in the database does not match the number of "
"hosts in the configuration. Database: %(db)d, configuration: %(conf)d"
msgstr ""
"Le nombre d'hôtes dans la base de données ne correspond pas au nombre "
"d'hôtes dans la configuration. Base: %(db)d, conf: %(conf)d."

#: src/vigilo/vigiconf/lib/validator.py:169
#, python-format
msgid ""
"The number of services entries in the database does not match the number "
"of services in the configuration. Database: %(db)d, configuration: "
"%(conf)d"
msgstr ""
"Le nombre de services dans la base de données ne correspond pas au nombre"
" d'hôtes dans la configuration. Base: %(db)d, conf: %(conf)d."

#: src/vigilo/vigiconf/lib/validator.py:183
#, python-format
msgid ""
"The number of apps loaded in the database does not match the number of "
"apps to deploy. Database: %(db)d, to deploy: %(deploy)d. Possible cause: "
"one or more app have no Vigilo server to be deployed on."
msgstr ""
"Le nombre d'applications chargées dans la base de données ne correspond "
"pas au nombre d'applications à déployer. Base de données : %(db)d, à "
"déployer : %(deploy)d. Cause possible : une ou plusieurs applications "
"n'ont pas de serveur Vigilo associé permettant de les déployer."

#: src/vigilo/vigiconf/lib/validator.py:201
#, python-format
msgid ""
"The number of ventilation entries in the database does not match the "
"number of host and apps. Database: %(db)d, should be: %(conf)d. Possible "
"cause: one or more application have no Vigilo server to be deployed on."
msgstr ""
"Le nombre d'associations de ventilation dans la base de données ne "
"correspond pas au nombre d'hôtes et d'applications. Base: %(db)d, devrait"
" être: %(conf)d. Cause possible : une ou plusieurs application(s) n'a pas"
" de serveur Vigilo où être déployée."

#: src/vigilo/vigiconf/lib/validator.py:235
#, python-format
msgid ""
"%(nb_gens)d generators exist whereas %(nb_apps)d applications have been "
"configured"
msgstr ""
"%(nb_gens)d générateurs existent tandis que %(nb_apps)d applications ont "
"été configurées"

#: src/vigilo/vigiconf/lib/validator.py:242
#, python-format
msgid "########> Error in %(source)s (object %(object)s): %(error)s"
msgstr "########> Erreur dans %(source)s (objet %(object)s) : %(error)s"

#: src/vigilo/vigiconf/lib/validator.py:249
#, python-format
msgid "====> Warning in %(source)s (object %(object)s): %(error)s"
msgstr "====> Avertissement dans %(source)s (object %(object)s) : %(error)s"

#: src/vigilo/vigiconf/lib/validator.py:255
#, python-format
msgid "%d errors"
msgstr "%d erreurs"

#: src/vigilo/vigiconf/lib/validator.py:256
#, python-format
msgid "%d warnings"
msgstr "%d avertissements"

#: src/vigilo/vigiconf/lib/validator.py:258
#, python-format
msgid ""
"%(nbGenerators)d generators have configured %(nbHosts)d hosts on "
"%(nbServers)d servers."
msgstr ""
"%(nbGenerators)d générateurs ont configuré %(nbHosts)d hôtes sur "
"%(nbServers)d serveurs."

#: src/vigilo/vigiconf/lib/validator.py:260
#, python-format
msgid "%(filesWritten)d files have been generated in %(dirsCreated)d directories"
msgstr "%(filesWritten)d fichiers ont été générés dans %(dirsCreated)d dossiers"

#: src/vigilo/vigiconf/lib/confclasses/host.py:133
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:160
#, python-format
msgid "The \"%s\" attribute has been deprecated. Please use \"%s\" instead."
msgstr ""
"L'attribut \"%s\" est obsolète. Veuillez utiliser l'attribut \"%s\" à la "
"place."

#: src/vigilo/vigiconf/lib/confclasses/host.py:184
#, python-format
msgid ""
"Test \"%(test_name)s\" on \"%(host)s\" needs the following arguments: "
"%(args)s (and only those)"
msgstr ""
"Le test \"%(test_name)s\" sur \"%(host)s\" nécessite les arguments "
"suivants: %(args)s (et uniquement ceux-là)"

#: src/vigilo/vigiconf/lib/confclasses/host.py:544
#, python-format
msgid "Wrong datasource in graph '%(graph)s': %(ds)s"
msgstr "Source de données incorrecte sur le graphe '%(graph)s' : %(ds)s"

#: src/vigilo/vigiconf/lib/confclasses/host.py:777
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:279
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:92
#, python-format
msgid "Invalid XML validation schema %(schema)s: %(error)s"
msgstr "Le schéma %(schema)s n'est pas valide : %(error)s"

#: src/vigilo/vigiconf/lib/confclasses/host.py:783
#: src/vigilo/vigiconf/lib/confclasses/host.py:803
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:285
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:305
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:98
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:118
#, python-format
msgid ""
"Error reading %(file)s, make sure the permissions are set "
"correctly.Message: %(error)s."
msgstr ""
"Erreur lors de la lecture du fichier %(file)s, assurez-vous que les "
"permissions sur le fichier sont correctement réglées. Erreur : %(error)s."

#: src/vigilo/vigiconf/lib/confclasses/host.py:800
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:302
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:115
#, python-format
msgid "XML syntax error in %(file)s: %(error)s"
msgstr "Erreur de syntaxe XML dans \"%(file)s\" : %(error)s"

#: src/vigilo/vigiconf/lib/confclasses/host.py:811
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:313
#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:126
#, python-format
msgid "XML validation failed: %(error)s"
msgstr "Échec de la validation XML : %(error)s"

#: src/vigilo/vigiconf/lib/confclasses/host.py:864
#, python-format
msgid "Invalid ventilation group: %s"
msgstr "Groupe de ventilation non valide : %s"

#: src/vigilo/vigiconf/lib/confclasses/host.py:898
#, python-format
msgid "Invalid weight value for test %(test)s on host %(host)s: %(weight)r"
msgstr ""
"Valeur du poids non valide pour le test %(test)s sur l'hôte %(host)s : "
"%(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/host.py:948
#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:120
#: src/vigilo/vigiconf/loaders/hlservice.py:135
#, python-format
msgid "Invalid group name (%s)"
msgstr "Nom de groupe non valide (%s)"

#: src/vigilo/vigiconf/lib/confclasses/host.py:957
#, python-format
msgid "Invalid weight value for host %(host)s: %(weight)r"
msgstr "Valeur du poids non valide pour l'hôte %(host)s : %(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/host.py:971
#, python-format
msgid "You must associate host \"%s\" with at least one group."
msgstr "Vous devez associer l'hôte \"%s\" avec au moins un groupe."

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:392
#, python-format
msgid "Invalid weight value for test %(test)s in template %(tpl)s: %(weight)r"
msgstr ""
"Valeur du poids non valide pour le test %(test)s dans le patron %(tpl)s :"
" %(weight)r"

#: src/vigilo/vigiconf/lib/confclasses/hosttemplate.py:417
#, python-format
msgid "Invalid weight value for template %(tpl)s: %(weight)r"
msgstr "Valeur du poids non valide dans le patron %(tpl)s : %(weight)r"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:110
msgid "Generation failed!"
msgstr "Échec de la génération"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:113
msgid "Generation successful"
msgstr "Génération réussie"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:143
msgid "Database commit successful"
msgstr "Enregistrement en base réussi"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:147
msgid "Database commit failed"
msgstr "Échec du COMMIT dans la base de données"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:156
msgid "All servers are up-to-date. No restart needed."
msgstr "Tous les serveurs sont à jour. Un redémarrage n'est pas nécessaire."

#: src/vigilo/vigiconf/lib/dispatchator/base.py:171
#, python-format
msgid "Current revision in the repository : %d"
msgstr "Révision actuelle dans le dépôt : %d"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:179
msgid "(should be deployed)"
msgstr "(devrait être déployé)"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:181
msgid "(should restart)"
msgstr "(devrait redémarrer)"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:182
#, python-format
msgid "Revisions for server %(server)s : %(rev)s%(dep)s%(restart)s"
msgstr "Révisions pour le serveur %(server)s : %(rev)s%(dep)s%(restart)s"

#: src/vigilo/vigiconf/lib/dispatchator/base.py:188
#, python-format
msgid "Cannot get revision for server: %(server)s. REASON : %(reason)s"
msgstr ""
"Impossible d'obtenir la révision pour le serveur %(server)s. RAISON : "
"%(reason)s"

#: src/vigilo/vigiconf/lib/dispatchator/factory.py:51
msgid ""
"You are trying remote deployment on the Community edition. This feature "
"is only available in the Enterprise edition. Aborting."
msgstr ""
"Vous tentez un déploiement distant dans l'Édition Communauté. Cette "
"fonctionnalité n'est disponible que dans l'Édition Entreprise. "
"Annulation."

#: src/vigilo/vigiconf/lib/dispatchator/local.py:44
msgid ""
"Vigilo server management is only available in the Enterprise edition. "
"Aborting."
msgstr ""
"La gestion des serveurs Vigilo n'est possible qu'avec l'édition "
"Entreprise. Abandon."

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:64
msgid ""
"you can't go back to a former revision if you have modified your "
"configuration. Use 'svn revert' to cancel your modifications"
msgstr ""
"vous ne pouvez pas revenir à une révision précédente après avoir modifié "
"votre configuration. Utilisez 'svn revert' pour annuler vos modifications"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:86
#, python-format
msgid "can't get the SVN status for the configuration dir: %s"
msgstr "impossible d'obtenir le statut SVN du dossier de configuration : %s"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:131
msgid "Not updating because the 'svnrepository' configuration parameter is empty"
msgstr ""
"Pas de mise à jour car le paramètre 'svnrepository' de la configuration "
"est vide"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:149
msgid "Error while syncing the SVN directory"
msgstr "Erreur lors de la synchronisation du dépôt SVN"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:166
#, python-format
msgid "Can't add %(path)s in repository: %(error)s"
msgstr "Impossible d'ajouter %(path)s au dépôt : %(error)s"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:189
#, python-format
msgid "can't remove %(path)s from repository: %(error)s"
msgstr "impossible de supprimer %(path)s du dépôt : %(error)s"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:200
msgid ""
"Not committing because the 'svnrepository' configuration parameter is "
"empty"
msgstr ""
"Pas d'enregistrement car le paramètre 'svnrepository' de la configuration"
" est vide"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:212
#, python-format
msgid "can't commit the configuration dir in SVN: %s"
msgstr "impossible d'enregistrer le dossier de configuration sur le dépôt : %s"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:217
msgid "SVN commit successful"
msgstr "Enregistrement SVN réussi"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:231
#, python-format
msgid ""
"can't execute the request to update the local copy. COMMAND %(cmd)s "
"FAILED. REASON: %(reason)s"
msgstr ""
"impossible de mettre à jour la copie locale. ÉCHEC DE LA COMMANDE "
"%(cmd)s. RAISON : %(reason)s"

#: src/vigilo/vigiconf/lib/dispatchator/revisionmanager.py:271
#, python-format
msgid "can't execute the request to get the current revision: %s"
msgstr "impossible d'obtenir la révision courante : %s"

#: src/vigilo/vigiconf/lib/generators/base.py:79
msgid "Generators must define the generate_host() method"
msgstr "Les générateurs doivent définir la méthode generate_host()."

#: src/vigilo/vigiconf/lib/generators/file.py:99
#, python-format
msgid "No such template: %s"
msgstr "Patron de fichier introuvable : %s"

#: src/vigilo/vigiconf/lib/generators/manager.py:98
#: src/vigilo/vigiconf/lib/generators/manager.py:312
#, python-format
msgid "Generated configuration for %s"
msgstr "Configuration générée pour %s"

#: src/vigilo/vigiconf/lib/generators/manager.py:132
msgid "Computing ventilation"
msgstr "Calcul de la ventilation"

#: src/vigilo/vigiconf/lib/generators/manager.py:147
msgid "Running generators"
msgstr "Lancement des générateurs"

#: src/vigilo/vigiconf/lib/generators/manager.py:169
#, python-format
msgid "Generating configuration for %s"
msgstr "Génération de la configuration pour %s"

#: src/vigilo/vigiconf/lib/generators/manager.py:175
msgid "Running database generators"
msgstr "Lancement des générateurs en base de données"

#: src/vigilo/vigiconf/lib/generators/manager.py:188
#, python-format
msgid "%(errtype)s in application %(app)s: %(error)s"
msgstr "%(errtype)s dans l'application %(app)s : %(error)s"

#: src/vigilo/vigiconf/lib/generators/manager.py:209
msgid "Can't find the metro server for the RRD-based services"
msgstr ""
"Impossible de trouver le serveur de métrologie pour les services basés "
"sur les RRD"

#: src/vigilo/vigiconf/lib/generators/manager.py:221
#: src/vigilo/vigiconf/lib/generators/manager.py:231
#, python-format
msgid ""
"The metrology server %s must be supervised for the RRD-based services to "
"work"
msgstr ""
"Le serveur de métrologie %s doit être supervisé pour pouvoir utiliser des"
" services basés sur les RRD"

#: src/vigilo/vigiconf/lib/generators/map.py:80
#, python-format
msgid "The map group %s has not been added by the install procedure"
msgstr "Le groupe de cartes %s n'a pas été ajouté par la procédure d'installation"

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:61
msgid "The 'load' method must be redefined"
msgstr "La méthode 'load' doit être redéfinie"

#: src/vigilo/vigiconf/lib/loaders/dbloader.py:115
msgid ""
"The key attribute must be defined, or the get_key() method must be "
"redefined"
msgstr ""
"L'attribut key doit être défini, ou la méthode get_key() doit être "
"rédéfinie"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:87
#, python-format
msgid "XSD file does not exist: %s"
msgstr "Le fichier XSD n'existe pas : %s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:177
#, python-format
msgid "End tag mismatch error: %(start)s/%(end)s"
msgstr "Balises de début/fin différentes : %(start)s/%(end)s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:184
#, python-format
msgid "Syntax error in \"%(path)s\": %(error)s"
msgstr "Erreur de syntaxe dans \"%(path)s\" : %(error)s"

#: src/vigilo/vigiconf/lib/loaders/xmlloader.py:355
#, python-format
msgid "Can't find an item matching %s"
msgstr "Impossible de trouver un élément correspondant à %s"

#: src/vigilo/vigiconf/lib/server/base.py:140
#, python-format
msgid ""
"Can't activate the configuration on %(server)s. COMMAND %(cmd)s FAILED. "
"REASON: %(reason)s"
msgstr ""
"Impossible d'activer la configuration sur %(server)s. ÉCHEC DE LA "
"COMMANDE %(cmd)s. RAISON : %(reason)s"

#: src/vigilo/vigiconf/lib/server/base.py:160
#, python-format
msgid "Can't tar config for server %(server)s: %(error)s"
msgstr "Impossible d'archiver la configuration du serveur %(server)s: %(error)s"

#: src/vigilo/vigiconf/lib/server/base.py:175
#, python-format
msgid "%s : deployement successful."
msgstr "%s : déploiement réussi."

#: src/vigilo/vigiconf/lib/server/base.py:192
#, python-format
msgid "Cannot copy files (%(from)s to %(to)s): %(error)s."
msgstr "Impossible de copier les fichier (de %(from)s vers %(to)s) : %(error)s."

#: src/vigilo/vigiconf/lib/server/base.py:259
#, python-format
msgid "Cannot write the revision file: %s"
msgstr "Impossible d'écrire le fichier de révision : %s"

#: src/vigilo/vigiconf/lib/server/base.py:263
#, python-format
msgid "Deployed: %d"
msgstr "Déployés : %d"

#: src/vigilo/vigiconf/lib/server/base.py:264
#, python-format
msgid "Installed: %d"
msgstr "Installés : %d"

#: src/vigilo/vigiconf/lib/server/base.py:265
#, python-format
msgid "Previous: %d"
msgstr "Précédent : %d"

#: src/vigilo/vigiconf/lib/server/factory.py:75
msgid "On the Community Edition, you can only use localhost"
msgstr "Dans l'Édition Communauté, seul localhost est utilisable"

#: src/vigilo/vigiconf/lib/server/factory.py:89
msgid ""
"You are trying remote server management with the Community edition. This "
"feature is only available in the Enterprise edition. Aborting."
msgstr ""
"Vous tentez un déploiement distant dans l'Édition Communautaire. Cette "
"fonctionnalité n'est disponible que dans l'Édition Entreprise. "
"Annulation."

#: src/vigilo/vigiconf/lib/server/local.py:62
#, python-format
msgid "Can't deploy the tar archive for server %(server)s: %(error)s"
msgstr "Impossible de déployer l'archive tar du serveur %(server)s: %(error)s"

#: src/vigilo/vigiconf/lib/server/manager.py:125
msgid "All servers are up-to-date, no deployment needed."
msgstr "Tous les serveurs sont à jour. Un déploiement n'est pas nécessaire."

#: src/vigilo/vigiconf/lib/server/manager.py:131
msgid ""
"The configurations files have not been transfered on every server. See "
"above for more information."
msgstr ""
"Les fichiers de configuration n'ont pas pu être transférés à tous les "
"serveurs. Lisez les messages précédents pour plus d'information."

#: src/vigilo/vigiconf/lib/server/manager.py:147
msgid "Switch directories was not successful on each server."
msgstr "La permutation de dossier a échoué sur certains serveurs."

#: src/vigilo/vigiconf/lib/server/remote.py:81
#, python-format
msgid "Invalid server name: %(servername)s. Available servers: %(servers)s"
msgstr ""
"Nom de serveur non valide : %(servername)s. Serveur disponibles : "
"%(servers)s"

#: src/vigilo/vigiconf/lib/server/remote.py:106
#, python-format
msgid "Cannot find SSH config file: %s"
msgstr "Impossible de trouver le fichier de configuration SSH : %s"

#: src/vigilo/vigiconf/lib/server/remote.py:144
#, python-format
msgid "The archive file does not exist: %s"
msgstr "L'archive n'existe pas : %s"

#: src/vigilo/vigiconf/lib/server/remote.py:149
#, python-format
msgid "Can't copy the configuration archive to %(server)s: %(error)s"
msgstr ""
"Impossible de copier l'archive' de configuration sur %(server)s : "
"%(error)s"

#: src/vigilo/vigiconf/lib/server/remote.py:164
#, python-format
msgid "Can't deploy the configuration for server %(server)s: %(error)s"
msgstr "Impossible de déployer la configuration du serveur %(server)s : %(error)s"

#: src/vigilo/vigiconf/lib/server/remote.py:189
#: src/vigilo/vigiconf/lib/server/remote.py:203
#, python-format
msgid "The Vigilo server %s does not exist"
msgstr "Le serveur Vigilo %s n'existe pas."

#: src/vigilo/vigiconf/lib/server/remote.py:192
#, python-format
msgid "The Vigilo server %s is already disabled"
msgstr "Le serveur Vigilo %s est déjà désactivé."

#: src/vigilo/vigiconf/lib/server/remote.py:206
#, python-format
msgid "The Vigilo server %s is already enabled"
msgstr "Le serveur Vigilo %s est déjà activé."

#: src/vigilo/vigiconf/lib/ventilation/remote.py:148
#, python-format
msgid ""
"Could not determine how to ventilate host \"%s\". Affect some groups to "
"this host or use the ventilation attribute."
msgstr ""
"Impossible de déterminer comment ventiler l'hôte \"%s\". Affectez cet "
"hôte à un groupe ou utilisez l'attribut 'ventilation'."

#: src/vigilo/vigiconf/lib/ventilation/remote.py:154
#, python-format
msgid ""
"Found multiple candidates for ventilation (%(candidates)r) on "
"\"%(host)s\", use the ventilation attribute to select one."
msgstr ""
"Plusieurs candidats (%(candidates)r) ont été trouvés pour la ventilation "
"de \"%(host)s\", utilisez l'attribut 'ventilation' pour en choisir un."

#: src/vigilo/vigiconf/lib/ventilation/remote.py:265
#, python-format
msgid ""
"No server available for the appgroup %(appgroup)s and the hostgroup "
"%(hostgroup)s, skipping it"
msgstr ""
"Pas de serveur disponible pour le groupe d'applications %(appgroup)s et "
"le groupe d'hôtes %(hostgroup)s, ils seront ignorés"

#: src/vigilo/vigiconf/lib/ventilation/remote.py:278
#, python-format
msgid ""
"Trying to ventilate hostgroup %(hostgroup)s for appgroup %(appgroup)s, "
"but the mapping is not in appsGroupsByServer."
msgstr ""
"Tentative de ventilation du groupe d'hôte %(hostgroup)s pour le groupe "
"d'applications %(appgroup)s, mais l'association n'existe pas dans "
"appsGroupsByServer."

#: src/vigilo/vigiconf/loaders/group.py:133
msgid "Loading groups"
msgstr "Chargement des groupes"

#: src/vigilo/vigiconf/loaders/hlservice.py:89
#, python-format
msgid "Unknown group \"%(group)s\" in HLS \"%(hls)s\"."
msgstr "Groupe inconnu \"%(group)s\" sur le SHN \"%(hls)s\"."

#: src/vigilo/vigiconf/loaders/hlservice.py:125
#, python-format
msgid "Invalid operator \"%(operator)s\". Possible values: %(possibilities)s"
msgstr ""
"Opérateur non valide \"%(operator)s\". Valeurs possibles : "
"%(possibilities)s"

#: src/vigilo/vigiconf/loaders/hlservice.py:175
#, python-format
msgid ""
"syntax error in HLS %(hls)s: could not find a group matching path "
"\"%(path)s\""
msgstr ""
"erreur de syntaxe sur le SHN %(hls)s : impossible de trouver un groupe "
"correspondant au chemin \"%(path)s\""

#: src/vigilo/vigiconf/loaders/host.py:73
#, python-format
msgid "Deleting leftover config file from database: %s"
msgstr ""
"Suppression d'un fichier de configuration obsolète dans la base de "
"données: %s"

#: src/vigilo/vigiconf/loaders/host.py:79
msgid "Loading hosts"
msgstr "Chargement des hôtes"

#: src/vigilo/vigiconf/loaders/host.py:125
#, python-format
msgid "Loading host %s"
msgstr "Chargement de l'hôte %s"

#: src/vigilo/vigiconf/loaders/host.py:265
msgid "Done loading hosts"
msgstr "Chargement des hôtes terminé"

#: src/vigilo/vigiconf/loaders/host.py:288
#, python-format
msgid "Unknown group \"%(group)s\" in host \"%(host)s\"."
msgstr "Groupe inconnu \"%(group)s\" sur l'hôte \"%(host)s\"."

#: src/vigilo/vigiconf/loaders/host.py:315
#, python-format
msgid ""
"syntax error in host %(host)s: could not find a group matching path "
"\"%(path)s\""
msgstr ""
"erreur de syntaxe sur l'hôte %(host)s : impossible de trouver un groupe "
"correspondant au chemin \"%(path)s\""

#: src/vigilo/vigiconf/loaders/topology.py:94
#, python-format
msgid "Not a Dependency: %s"
msgstr "Pas une dépendance : %s"

#: src/vigilo/vigiconf/loaders/topology.py:109
msgid "No dependent supervised item"
msgstr "Aucun élément supervisé dépendant"

#: src/vigilo/vigiconf/loaders/ventilation.py:115
#, python-format
msgid "Can't load the ventilation in database: the host %s is not in database yet"
msgstr ""
"Impossible de charger la ventilation en base de données : l'hôte %s \"\n"
"\"n'existe pas encore dans la base de données"

#: src/vigilo/vigiconf/loaders/ventilation.py:151
#, python-format
msgid ""
"The application %s has been removed from the configuration, it needs to "
"be stopped manually"
msgstr ""
"L'application %s a été retirée de la configuration, elle doit être "
"arrêtée manuellement"

#~ msgid "Recieved unhandled message type: %(msgtype)s"
#~ msgstr ""
